behaviors:
  PacMan:
    behavioral_cloning: null
    checkpoint_interval: 500000
    framework: pytorch
    hyperparameters: {batch_size: 1024, beta: 0.005, buffer_size: 10240, epsilon: 0.2,
      lambd: 0.95, learning_rate: 0.0003, learning_rate_schedule: linear, num_epoch: 5}
    init_path: null
    keep_checkpoints: 5
    max_steps: 10000000
    network_settings: {hidden_units: 256, memory: null, normalize: false, num_layers: 2,
      vis_encode_type: simple}
    reward_signals:
      extrinsic: {gamma: 0.99, strength: 1.0}
    self_play: {initial_elo: 1200.0, play_against_latest_model_ratio: 0.5, save_steps: 50000,
      swap_steps: 2000, team_change: 100000, window: 10}
    summary_freq: 50000
    threaded: false
    time_horizon: 1000
    trainer_type: ppo
checkpoint_settings: {force: false, inference: false, initialize_from: null, load_model: false,
  resume: true, run_id: Pacman_simple, train_model: false}
debug: false
default_settings: null
engine_settings: {capture_frame_rate: 60, height: 84, no_graphics: true, quality_level: 5,
  target_frame_rate: -1, time_scale: 20, width: 84}
env_settings: {base_port: 5005, env_args: null, env_path: /content/Pacman/pacman.x86_64,
  num_envs: 1, seed: -1}
environment_parameters: null
